/**
 * Rules data layer.
 *
 * A Rule is a conditional expression that includes or excludes clauses from a
 * clause set based on clause set data (contract type, dollar threshold, agency,
 * place of performance, and so on).
 *
 * `lastUpdated` is stored as an ISO 8601 string so it sorts correctly. Pages
 * format it for display with `formatRuleTimestamp`.
 */

export interface Rule {
  id: number
  name: string
  status: 'Active' | 'Draft'
  /** Standard rules ship with the solution. Custom rules are authored by the agency. */
  source: 'Standard' | 'Custom'
  /** Number of individual conditions across the rule. */
  conditions: number
  /** Number of condition groups wrapping those conditions. */
  conditionGroups: number
  includedClauses: number
  excludedClauses: number
  /** ISO 8601 timestamp. */
  lastUpdated: string
  createdBy: string
  modifiedBy: string
}

const rules: Rule[] = [
  {
    id: 1,
    name: 'pktestrule2',
    status: 'Active',
    source: 'Custom',
    conditions: 1,
    conditionGroups: 0,
    includedClauses: 1,
    excludedClauses: 1,
    lastUpdated: '2026-10-01T15:35:00',
    createdBy: 'john.smith',
    modifiedBy: 'john.smith',
  },
  {
    id: 2,
    name: 'pktestrule1',
    status: 'Active',
    source: 'Standard',
    conditions: 1,
    conditionGroups: 0,
    includedClauses: 1,
    excludedClauses: 1,
    lastUpdated: '2026-09-29T15:40:00',
    createdBy: 'john.smith',
    modifiedBy: 'alice.chen',
  },
  {
    id: 3,
    name: 'Clause 19.24.2124 Inclusion',
    status: 'Draft',
    source: 'Custom',
    conditions: 2,
    conditionGroups: 1,
    includedClauses: 0,
    excludedClauses: 0,
    lastUpdated: '2026-09-29T14:29:00',
    createdBy: 'alice.chen',
    modifiedBy: 'alice.chen',
  },
  {
    id: 4,
    name: 'Clause 19.24.2124 Inclusion',
    status: 'Draft',
    source: 'Standard',
    conditions: 1,
    conditionGroups: 0,
    includedClauses: 0,
    excludedClauses: 0,
    lastUpdated: '2026-09-29T14:22:00',
    createdBy: 'alice.chen',
    modifiedBy: 'bob.martinez',
  },
  {
    id: 5,
    name: 'Test Hitesh 1',
    status: 'Active',
    source: 'Custom',
    conditions: 1,
    conditionGroups: 0,
    includedClauses: 2,
    excludedClauses: 1,
    lastUpdated: '2026-09-24T00:18:00',
    createdBy: 'bob.martinez',
    modifiedBy: 'bob.martinez',
  },
  {
    id: 6,
    name: 'Task Assignment to Contracting Officer',
    status: 'Active',
    source: 'Standard',
    conditions: 4,
    conditionGroups: 1,
    includedClauses: 16,
    excludedClauses: 3,
    lastUpdated: '2026-09-21T23:12:00',
    createdBy: 'carol.white',
    modifiedBy: 'john.smith',
  },
  {
    id: 7,
    name: 'GCA Rule',
    status: 'Active',
    source: 'Custom',
    conditions: 4,
    conditionGroups: 3,
    includedClauses: 55,
    excludedClauses: 0,
    lastUpdated: '2026-09-18T22:31:00',
    createdBy: 'david.kim',
    modifiedBy: 'david.kim',
  },
  {
    id: 8,
    name: 'Compliance Skip Check Rule',
    status: 'Active',
    source: 'Standard',
    conditions: 1,
    conditionGroups: 0,
    includedClauses: 0,
    excludedClauses: 0,
    lastUpdated: '2026-09-18T14:54:00',
    createdBy: 'carol.white',
    modifiedBy: 'carol.white',
  },
  {
    id: 9,
    name: 'rock Val Test',
    status: 'Active',
    source: 'Custom',
    conditions: 1,
    conditionGroups: 0,
    includedClauses: 2,
    excludedClauses: 0,
    lastUpdated: '2026-09-17T22:00:00',
    createdBy: 'bob.martinez',
    modifiedBy: 'bob.martinez',
  },
  {
    id: 10,
    name: 'Din Test',
    status: 'Active',
    source: 'Standard',
    conditions: 2,
    conditionGroups: 2,
    includedClauses: 2,
    excludedClauses: 0,
    lastUpdated: '2026-09-10T20:35:00',
    createdBy: 'david.kim',
    modifiedBy: 'alice.chen',
  },
  {
    id: 11,
    name: 'Commercial Item Acquisition Threshold',
    status: 'Active',
    source: 'Standard',
    conditions: 3,
    conditionGroups: 1,
    includedClauses: 12,
    excludedClauses: 2,
    lastUpdated: '2026-09-09T17:48:00',
    createdBy: 'john.smith',
    modifiedBy: 'john.smith',
  },
  {
    id: 12,
    name: 'Small Business Set-Aside Inclusion',
    status: 'Active',
    source: 'Standard',
    conditions: 2,
    conditionGroups: 0,
    includedClauses: 8,
    excludedClauses: 1,
    lastUpdated: '2026-09-08T11:15:00',
    createdBy: 'alice.chen',
    modifiedBy: 'carol.white',
  },
  {
    id: 13,
    name: 'Service Contract Labor Standards',
    status: 'Active',
    source: 'Standard',
    conditions: 3,
    conditionGroups: 2,
    includedClauses: 6,
    excludedClauses: 0,
    lastUpdated: '2026-09-07T09:02:00',
    createdBy: 'carol.white',
    modifiedBy: 'carol.white',
  },
  {
    id: 14,
    name: 'Construction Contract Over $2M',
    status: 'Draft',
    source: 'Custom',
    conditions: 4,
    conditionGroups: 2,
    includedClauses: 21,
    excludedClauses: 4,
    lastUpdated: '2026-09-04T16:30:00',
    createdBy: 'david.kim',
    modifiedBy: 'david.kim',
  },
  {
    id: 15,
    name: 'Cost Accounting Standards Applicability',
    status: 'Active',
    source: 'Standard',
    conditions: 5,
    conditionGroups: 2,
    includedClauses: 9,
    excludedClauses: 3,
    lastUpdated: '2026-09-03T13:44:00',
    createdBy: 'john.smith',
    modifiedBy: 'bob.martinez',
  },
  {
    id: 16,
    name: 'Trade Agreements Act Exclusion',
    status: 'Active',
    source: 'Standard',
    conditions: 2,
    conditionGroups: 1,
    includedClauses: 0,
    excludedClauses: 7,
    lastUpdated: '2026-09-02T10:20:00',
    createdBy: 'alice.chen',
    modifiedBy: 'alice.chen',
  },
  {
    id: 17,
    name: 'Buy American Domestic Preference',
    status: 'Active',
    source: 'Standard',
    conditions: 3,
    conditionGroups: 1,
    includedClauses: 5,
    excludedClauses: 2,
    lastUpdated: '2026-09-01T15:05:00',
    createdBy: 'bob.martinez',
    modifiedBy: 'john.smith',
  },
  {
    id: 18,
    name: 'Simplified Acquisition Procedures',
    status: 'Active',
    source: 'Custom',
    conditions: 2,
    conditionGroups: 0,
    includedClauses: 4,
    excludedClauses: 11,
    lastUpdated: '2026-08-28T12:38:00',
    createdBy: 'carol.white',
    modifiedBy: 'carol.white',
  },
  {
    id: 19,
    name: 'IT Supply Chain Risk Screening',
    status: 'Draft',
    source: 'Custom',
    conditions: 6,
    conditionGroups: 3,
    includedClauses: 14,
    excludedClauses: 0,
    lastUpdated: '2026-08-27T18:52:00',
    createdBy: 'david.kim',
    modifiedBy: 'alice.chen',
  },
  {
    id: 20,
    name: 'Section 889 Telecom Prohibition',
    status: 'Active',
    source: 'Standard',
    conditions: 2,
    conditionGroups: 1,
    includedClauses: 3,
    excludedClauses: 0,
    lastUpdated: '2026-08-26T09:41:00',
    createdBy: 'john.smith',
    modifiedBy: 'john.smith',
  },
  {
    id: 21,
    name: 'Subcontracting Plan Requirement',
    status: 'Active',
    source: 'Standard',
    conditions: 3,
    conditionGroups: 1,
    includedClauses: 6,
    excludedClauses: 1,
    lastUpdated: '2026-08-25T14:17:00',
    createdBy: 'alice.chen',
    modifiedBy: 'bob.martinez',
  },
  {
    id: 22,
    name: 'Davis-Bacon Wage Determination',
    status: 'Active',
    source: 'Standard',
    conditions: 4,
    conditionGroups: 2,
    includedClauses: 10,
    excludedClauses: 0,
    lastUpdated: '2026-08-21T11:09:00',
    createdBy: 'carol.white',
    modifiedBy: 'david.kim',
  },
  {
    id: 23,
    name: 'Overseas Place of Performance',
    status: 'Draft',
    source: 'Custom',
    conditions: 3,
    conditionGroups: 1,
    includedClauses: 7,
    excludedClauses: 5,
    lastUpdated: '2026-08-20T16:55:00',
    createdBy: 'bob.martinez',
    modifiedBy: 'bob.martinez',
  },
  {
    id: 24,
    name: 'GSA Schedule Order Baseline',
    status: 'Active',
    source: 'Standard',
    conditions: 1,
    conditionGroups: 0,
    includedClauses: 18,
    excludedClauses: 0,
    lastUpdated: '2026-08-19T08:26:00',
    createdBy: 'david.kim',
    modifiedBy: 'carol.white',
  },
  {
    id: 25,
    name: 'Cybersecurity Maturity Model Certification',
    status: 'Active',
    source: 'Custom',
    conditions: 4,
    conditionGroups: 2,
    includedClauses: 9,
    excludedClauses: 1,
    lastUpdated: '2026-08-18T13:33:00',
    createdBy: 'john.smith',
    modifiedBy: 'alice.chen',
  },
  {
    id: 26,
    name: 'Cost Reimbursement Contract Type',
    status: 'Active',
    source: 'Standard',
    conditions: 2,
    conditionGroups: 1,
    includedClauses: 13,
    excludedClauses: 2,
    lastUpdated: '2026-08-14T15:12:00',
    createdBy: 'alice.chen',
    modifiedBy: 'alice.chen',
  },
  {
    id: 27,
    name: 'Firm Fixed Price Exclusions',
    status: 'Active',
    source: 'Standard',
    conditions: 2,
    conditionGroups: 0,
    includedClauses: 0,
    excludedClauses: 9,
    lastUpdated: '2026-08-13T10:47:00',
    createdBy: 'carol.white',
    modifiedBy: 'john.smith',
  },
  {
    id: 28,
    name: 'HUBZone Price Evaluation Preference',
    status: 'Draft',
    source: 'Custom',
    conditions: 3,
    conditionGroups: 1,
    includedClauses: 4,
    excludedClauses: 0,
    lastUpdated: '2026-08-12T17:21:00',
    createdBy: 'david.kim',
    modifiedBy: 'david.kim',
  },
  {
    id: 29,
    name: 'Service-Disabled Veteran-Owned Set-Aside',
    status: 'Active',
    source: 'Standard',
    conditions: 2,
    conditionGroups: 1,
    includedClauses: 5,
    excludedClauses: 1,
    lastUpdated: '2026-08-11T09:58:00',
    createdBy: 'bob.martinez',
    modifiedBy: 'carol.white',
  },
  {
    id: 30,
    name: 'Protest After Award Notification',
    status: 'Active',
    source: 'Standard',
    conditions: 1,
    conditionGroups: 0,
    includedClauses: 2,
    excludedClauses: 0,
    lastUpdated: '2026-08-07T14:04:00',
    createdBy: 'john.smith',
    modifiedBy: 'bob.martinez',
  },
  {
    id: 31,
    name: 'Economic Price Adjustment Threshold',
    status: 'Draft',
    source: 'Custom',
    conditions: 5,
    conditionGroups: 2,
    includedClauses: 8,
    excludedClauses: 3,
    lastUpdated: '2026-08-06T11:39:00',
    createdBy: 'alice.chen',
    modifiedBy: 'david.kim',
  },
  {
    id: 32,
    name: 'Government Furnished Property',
    status: 'Active',
    source: 'Standard',
    conditions: 3,
    conditionGroups: 1,
    includedClauses: 11,
    excludedClauses: 0,
    lastUpdated: '2026-08-05T16:48:00',
    createdBy: 'carol.white',
    modifiedBy: 'carol.white',
  },
  {
    id: 33,
    name: 'Options for Increased Quantity',
    status: 'Active',
    source: 'Standard',
    conditions: 2,
    conditionGroups: 0,
    includedClauses: 3,
    excludedClauses: 1,
    lastUpdated: '2026-08-04T08:53:00',
    createdBy: 'david.kim',
    modifiedBy: 'john.smith',
  },
  {
    id: 34,
    name: 'Micro-Purchase Threshold Exclusion',
    status: 'Active',
    source: 'Custom',
    conditions: 1,
    conditionGroups: 0,
    includedClauses: 0,
    excludedClauses: 24,
    lastUpdated: '2026-07-31T13:26:00',
    createdBy: 'bob.martinez',
    modifiedBy: 'alice.chen',
  },
  {
    id: 35,
    name: 'Equal Opportunity Compliance',
    status: 'Active',
    source: 'Standard',
    conditions: 2,
    conditionGroups: 1,
    includedClauses: 6,
    excludedClauses: 0,
    lastUpdated: '2026-07-30T10:11:00',
    createdBy: 'john.smith',
    modifiedBy: 'carol.white',
  },
  {
    id: 36,
    name: 'Anti-Kickback Procedures Baseline',
    status: 'Active',
    source: 'Standard',
    conditions: 1,
    conditionGroups: 0,
    includedClauses: 2,
    excludedClauses: 0,
    lastUpdated: '2026-07-29T15:37:00',
    createdBy: 'alice.chen',
    modifiedBy: 'alice.chen',
  },
  {
    id: 37,
    name: 'Rights in Technical Data',
    status: 'Draft',
    source: 'Custom',
    conditions: 4,
    conditionGroups: 2,
    includedClauses: 7,
    excludedClauses: 2,
    lastUpdated: '2026-07-28T12:02:00',
    createdBy: 'carol.white',
    modifiedBy: 'david.kim',
  },
  {
    id: 38,
    name: 'Indefinite Delivery Indefinite Quantity',
    status: 'Active',
    source: 'Standard',
    conditions: 3,
    conditionGroups: 1,
    includedClauses: 15,
    excludedClauses: 1,
    lastUpdated: '2026-07-24T17:44:00',
    createdBy: 'david.kim',
    modifiedBy: 'bob.martinez',
  },
  {
    id: 39,
    name: 'Sole Source Justification Required',
    status: 'Active',
    source: 'Custom',
    conditions: 3,
    conditionGroups: 1,
    includedClauses: 4,
    excludedClauses: 0,
    lastUpdated: '2026-07-23T09:19:00',
    createdBy: 'bob.martinez',
    modifiedBy: 'bob.martinez',
  },
  {
    id: 40,
    name: 'Progress Payments Eligibility',
    status: 'Active',
    source: 'Standard',
    conditions: 4,
    conditionGroups: 2,
    includedClauses: 9,
    excludedClauses: 2,
    lastUpdated: '2026-07-22T14:31:00',
    createdBy: 'john.smith',
    modifiedBy: 'john.smith',
  },
  {
    id: 41,
    name: 'Energy Efficient Product Procurement',
    status: 'Draft',
    source: 'Custom',
    conditions: 2,
    conditionGroups: 0,
    includedClauses: 3,
    excludedClauses: 0,
    lastUpdated: '2026-07-21T11:07:00',
    createdBy: 'alice.chen',
    modifiedBy: 'carol.white',
  },
  {
    id: 42,
    name: 'Drug-Free Workplace Requirement',
    status: 'Active',
    source: 'Standard',
    conditions: 2,
    conditionGroups: 1,
    includedClauses: 2,
    excludedClauses: 0,
    lastUpdated: '2026-07-17T16:23:00',
    createdBy: 'carol.white',
    modifiedBy: 'alice.chen',
  },
  {
    id: 43,
    name: 'Limitation of Funds Incremental',
    status: 'Active',
    source: 'Standard',
    conditions: 3,
    conditionGroups: 1,
    includedClauses: 5,
    excludedClauses: 1,
    lastUpdated: '2026-07-16T08:49:00',
    createdBy: 'david.kim',
    modifiedBy: 'david.kim',
  },
  {
    id: 44,
    name: 'Contractor Personnel Badging',
    status: 'Active',
    source: 'Custom',
    conditions: 4,
    conditionGroups: 2,
    includedClauses: 8,
    excludedClauses: 0,
    lastUpdated: '2026-07-15T13:14:00',
    createdBy: 'bob.martinez',
    modifiedBy: 'john.smith',
  },
  {
    id: 45,
    name: 'Inspection and Acceptance Terms',
    status: 'Active',
    source: 'Standard',
    conditions: 2,
    conditionGroups: 0,
    includedClauses: 6,
    excludedClauses: 1,
    lastUpdated: '2026-07-14T10:36:00',
    createdBy: 'john.smith',
    modifiedBy: 'carol.white',
  },
  {
    id: 46,
    name: 'Organizational Conflict of Interest',
    status: 'Draft',
    source: 'Custom',
    conditions: 5,
    conditionGroups: 3,
    includedClauses: 12,
    excludedClauses: 4,
    lastUpdated: '2026-07-10T15:58:00',
    createdBy: 'alice.chen',
    modifiedBy: 'bob.martinez',
  },
  {
    id: 47,
    name: 'Past Performance Evaluation Clause',
    status: 'Active',
    source: 'Standard',
    conditions: 1,
    conditionGroups: 0,
    includedClauses: 3,
    excludedClauses: 0,
    lastUpdated: '2026-07-09T12:27:00',
    createdBy: 'carol.white',
    modifiedBy: 'carol.white',
  },
  {
    id: 48,
    name: 'Novation and Change of Name',
    status: 'Active',
    source: 'Standard',
    conditions: 2,
    conditionGroups: 1,
    includedClauses: 2,
    excludedClauses: 0,
    lastUpdated: '2026-07-08T17:05:00',
    createdBy: 'david.kim',
    modifiedBy: 'alice.chen',
  },
  {
    id: 49,
    name: 'Termination for Convenience Terms',
    status: 'Active',
    source: 'Standard',
    conditions: 3,
    conditionGroups: 1,
    includedClauses: 7,
    excludedClauses: 2,
    lastUpdated: '2026-07-07T09:33:00',
    createdBy: 'bob.martinez',
    modifiedBy: 'david.kim',
  },
  {
    id: 50,
    name: 'Electronic Invoicing via IPP',
    status: 'Active',
    source: 'Custom',
    conditions: 2,
    conditionGroups: 0,
    includedClauses: 4,
    excludedClauses: 0,
    lastUpdated: '2026-07-03T14:52:00',
    createdBy: 'john.smith',
    modifiedBy: 'john.smith',
  },
  {
    id: 51,
    name: 'Privacy Act System of Records',
    status: 'Draft',
    source: 'Custom',
    conditions: 3,
    conditionGroups: 1,
    includedClauses: 5,
    excludedClauses: 1,
    lastUpdated: '2026-07-02T11:18:00',
    createdBy: 'alice.chen',
    modifiedBy: 'carol.white',
  },
  {
    id: 52,
    name: 'Recovered Material Certification',
    status: 'Active',
    source: 'Standard',
    conditions: 2,
    conditionGroups: 1,
    includedClauses: 3,
    excludedClauses: 0,
    lastUpdated: '2026-07-01T16:41:00',
    createdBy: 'carol.white',
    modifiedBy: 'bob.martinez',
  },
  {
    id: 53,
    name: 'Contract Closeout Documentation',
    status: 'Active',
    source: 'Standard',
    conditions: 1,
    conditionGroups: 0,
    includedClauses: 2,
    excludedClauses: 0,
    lastUpdated: '2026-06-30T08:24:00',
    createdBy: 'david.kim',
    modifiedBy: 'david.kim',
  },
  {
    id: 54,
    name: 'Warranty of Supplies Threshold',
    status: 'Active',
    source: 'Custom',
    conditions: 3,
    conditionGroups: 1,
    includedClauses: 6,
    excludedClauses: 2,
    lastUpdated: '2026-06-26T13:09:00',
    createdBy: 'bob.martinez',
    modifiedBy: 'alice.chen',
  },
  {
    id: 55,
    name: 'Prohibition on Certain Semiconductors',
    status: 'Draft',
    source: 'Custom',
    conditions: 4,
    conditionGroups: 2,
    includedClauses: 9,
    excludedClauses: 0,
    lastUpdated: '2026-06-25T15:46:00',
    createdBy: 'john.smith',
    modifiedBy: 'john.smith',
  },
  {
    id: 56,
    name: 'Alternate Dispute Resolution',
    status: 'Active',
    source: 'Standard',
    conditions: 2,
    conditionGroups: 0,
    includedClauses: 2,
    excludedClauses: 0,
    lastUpdated: '2026-06-24T10:03:00',
    createdBy: 'alice.chen',
    modifiedBy: 'carol.white',
  },
  {
    id: 57,
    name: 'Emergency Acquisition Flexibilities',
    status: 'Active',
    source: 'Custom',
    conditions: 5,
    conditionGroups: 2,
    includedClauses: 17,
    excludedClauses: 6,
    lastUpdated: '2026-06-23T17:29:00',
    createdBy: 'carol.white',
    modifiedBy: 'david.kim',
  },
]

export async function getRules(): Promise<Rule[]> {
  return rules
}

export async function getRule(id: number): Promise<Rule | undefined> {
  return rules.find(r => r.id === id)
}

export async function createRule(data: Omit<Rule, 'id'>): Promise<Rule> {
  const newRule = { ...data, id: Math.max(0, ...rules.map(r => r.id)) + 1 }
  rules.push(newRule)
  return newRule
}

export async function updateRule(id: number, data: Partial<Rule>): Promise<Rule | undefined> {
  const idx = rules.findIndex(r => r.id === id)
  if (idx === -1) return undefined
  rules[idx] = { ...rules[idx], ...data }
  return rules[idx]
}

export async function deleteRule(id: number): Promise<boolean> {
  const idx = rules.findIndex(r => r.id === id)
  if (idx === -1) return false
  rules.splice(idx, 1)
  return true
}

/** Formats an ISO timestamp the way the Rules grid displays it, e.g. "Oct 1, 2026 3:35 PM". */
export function formatRuleTimestamp(iso: string): string {
  const date = new Date(iso)
  if (Number.isNaN(date.getTime())) return iso
  const datePart = date.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  })
  const timePart = date.toLocaleTimeString('en-US', {
    hour: 'numeric',
    minute: '2-digit',
    hour12: true,
  })
  return `${datePart} ${timePart}`
}

/** Summarizes a rule's condition structure, e.g. "2 conditions • 1 group". */
export function formatRuleConditions(rule: Rule): string {
  const conditionLabel = `${rule.conditions} condition${rule.conditions === 1 ? '' : 's'}`
  const groupLabel = `${rule.conditionGroups} group${rule.conditionGroups === 1 ? '' : 's'}`
  return `${conditionLabel} • ${groupLabel}`
}
